name: "Bug report"
description: "Report a problem with YouTube Live Chat Overlay"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug.
        Please provide as much detail as possible so we can reproduce and fix it.

  - type: input
    id: summary
    attributes:
      label: "Short summary"
      description: "One sentence describing the problem"
      placeholder: "Overlay does not appear on a live stream"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "Steps to reproduce"
      description: "List the exact steps needed to see the problem."
      placeholder: |
        1. Go to ...
        2. Click ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected behavior"
      description: "What did you expect to happen?"
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: "Actual behavior"
      description: "What actually happened? Include screenshots if helpful."
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: "Script version"
      description: "From the userscript header or GitHub release tag"
      placeholder: "v0.1.0"

  - type: dropdown
    id: browser
    attributes:
      label: "Browser"
      options:
        - "Chrome"
        - "Edge"
        - "Firefox"
        - "Safari"
        - "Other (desktop)"
    validations:
      required: true

  - type: input
    id: userscript_manager
    attributes:
      label: "Userscript manager"
      placeholder: "Tampermonkey, Violentmonkey, ..."

  - type: checkboxes
    id: checks
    attributes:
      label: "Checklist"
      options:
        - label: "I am using a desktop browser"
          required: true
        - label: "I have tested with the latest release from GitHub"
          required: true
        - label: "I have checked existing issues for duplicates"
          required: true
